### ISSUE TITLE
Several questions about the model design

### ISSUE THREAD

**Issue by Nc-gif** [cocoon2wong/SocialCircle#5]
Hello, esteemed author!
Thank you so much for sharing your wonderful code. It has been incredibly helpful in my efforts to develop new methods. However, I find myself a bit confused about certain aspects of the model design, and I would greatly appreciate your insights.

1. Regarding the [obs=>f_traj](https://github.com/cocoon2wong/SocialCircle/blob/396fe658e21bbff1094fcc51fd59a1ec7d278afa/socialCircle/__sc_EV.py#L110) process: Could you kindly elaborate on the necessity of the FFT, outer, MaxPooling2D, flatten, and fully connected (fc) steps in this pipeline? Are there specific design considerations that led to these complex operations? 

2. About [concatenating f_social and f_traj](https://github.com/cocoon2wong/SocialCircle/blob/396fe658e21bbff1094fcc51fd59a1ec7d278afa/socialCircle/__sc_EV.py#L117C9-L117C60): Both have shapes of [B, 8, dim]. The 8 in f_social represents the angle partition, while the 8 in f_traj represents the historical time step. If these are directly concatenated, it seems like one time step and one angle partition will correspond. Is there any potential for information confusion here?

3. Concerning the [traj_targets + f_final => self.T (Transformer) module](https://github.com/cocoon2wong/SocialCircle/blob/396fe658e21bbff1094fcc51fd59a1ec7d278afa/socialCircle/__sc_EV.py#L132): What is the specific role of this module? I noticed that after obtaining f_final, it is not directly fed into a fully connected layer for future trajectory prediction, but rather passed through the Transformer module. Additionally, since f_traj already contains information about the target agent, why is traj_target still needed?

4. On using FFT for feature extraction in [obs=>traj_target](https://github.com/cocoon2wong/SocialCircle/blob/396fe658e21bbff1094fcc51fd59a1ec7d278afa/socialCircle/__sc_EV.py#L123): Instead of using neural networks, FFT is employed to extract low-dimensional features. Could you share the reasoning behind this choice?

5. Regarding [f_final=>adj](https://github.com/cocoon2wong/SocialCircle/blob/396fe658e21bbff1094fcc51fd59a1ec7d278afa/socialCircle/__sc_EV.py#L137): This operation maps [B, T, 128] to [B, T, 20], which seemingly indicates the influence of each historical time step on different future trajectories. Could you please provide more details on the logic and motivation behind this process?

Thank you once again for your time and guidance. I am eager to learn from your expertise and improve my understanding of your work.

**Comment by cocoon2wong** [comment]
Hi @Nc-gif !
Thank you for your questions and sorry for the late reply!

1. About Fourier Transforms
FFT is used to transform trajectories and help the network extract all trajectory-related features from the frequency domain rather than the time-space domain. For more details, please refer to our previous work "View vertically: A hierarchical network for trajectory prediction via fourier spectrums". In addition, the transform aims to view trajectories in a different view from those presented in the time-series directly. We hope that this transform, along with the frequency response properties of the trajectories in the spectrum, will lead to better prediction of the trajectories. Note that this transform may not be equivalent to what we generally think of as feature extraction, since energy is preserved in this process, as stated in Parseval's theorem. As for your mentioned point 4, this `trap_target` plays as the target value for queries when computing attentions in the Transformer decoder, shows the Transformer which forms of trajectories it should learn to predict (even though the used Transformers do not contain a direct output layer).

2. `outer + pooling + flatten + fc` when encoding observed trajectories
Such a combination is actually a bilinear structure, which is designed to capture interactions among different spectral dimensions (of trajectory spectrums after applying transforms like DFT). Please refer to our previous work "Another vertical view: A hierarchical network for heterogeneous trajectory prediction via spectrums", and we have explained in detail why we have to design such structure when forecasting trajectories.

3. The concatenating of trajectory features and SocialCircle
We concatenate them together because they are both in the form of sequences, although one is a time series and the other is an angle-based sequence. This process is more about what we want the network to learn about the noteworthy parts of these sequences rather than the connections between them. As for your comment about data confusion, we also tried setting a larger number of partitions, like 12, 24, 36, etc., and verifying that whether or not the network would focus only on those partitions with only trajectories (zero paddings are applied on the trajectory features). The code can be found in the improved SocialCircle+ repository:
https://github.com/cocoon2wong/SocialCirclePlus/blob/e624887035adac9e008179de5628c6c09415a180/socialCircle/ev_sc.py#L121-L124
There are some corresponding 36-partition weights in the torch version of [weights repository](https://github.com/cocoon2wong/Project-Monandaeg/tree/SocialCircle/_variations), but these weights need to be loaded within the code in the [SocialCirclePlus]([https://github.com/cocoon2wong/SocialCirclePlus](https://github.com/cocoon2wong/SocialCirclePlus/blob/e624887035adac9e008179de5628c6c09415a180/socialCircle/ev_sc.py#L121-L124)) repository.
Through the experimental results, we found that the different partition features and trajectory features of SocialCircle do not interfere with each other significantly, especially when the number of partitions is quite different, e.g., 8 vs. 32. That is, SC does not appear to focus only on the first 8 partitions in this setup. The contributions of the other partitions are not compressed directly. Although it is difficult to quantitatively analyze whether this confusion exists and has a negative impact through the data.
It is well worth continuing to explore your consideration!

4. About the Transformer
Transformers are used to extract deep features of input trajectories, like other image-related tasks, by additionally considering the attention mechanism. It is indeed made up of multiple fully-connected layers, as you said. Please refer to their paper "Attention is all you need" for more details of why it could better encode features. In our usages, `traj_target` is the target value for queries in the Transformer decoder, while the `f_final` plays as keys and queries in both Transformer encoder and decoder.

5. About the `adj`
This part relates to our previous work "Msn: multi-style network for trajectory prediction". It achieves 20 predictions in a single network inference by constructing a 1*20 (note that 20 here denotes the number of generated trajectories, the `K` mentioned in most of the papers) trainable convolutional kernel that introduces 20 different decoding channels in a single network inference. 
https://github.com/cocoon2wong/SocialCircle/blob/363bcd6c26edab459fe7949d88676daf1fe3e744/socialCircle/ev_sc.py#L143-L146
Using your symbols, the `adj` is the kernel, with shape `[B, T, 20]`. It then multiplies with the `f_final` (with shape `[B, T, 128]`), and the output `f_multi` has the shape `[B, 20, 128]`. This step is performed in order to aggregate information from all observed moments and to achieve multi-path predictions in 20 different ways.

I hope these could help you!
Conghao Wong

**Comment by Nc-gif** [comment]
Thank you so much for your detailed and thorough response! Your explanations have been incredibly helpful and have really cleared up my understanding of the model. I really appreciate the time and effort you put into addressing my questions. Wishing you success in your research！
